version: '3'

x-airflow-common: &airflow-common
  image: airflow-dolar-project:2.9.2
  build: .
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - PYTHONPATH=/opt/airflow
    - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    - _AIRFLOW__WWW_USER_USERNAME=${_AIRFLOW_WWW_USER_USERNAME}
    - _AIRFLOW__WWW_USER_PASSWORD=${_AIRFLOW_WWW_USER_PASSWORD}
    - AIRFLOW_UID=${AIRFLOW_UID:-50000}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
    - ./charts:/opt/airflow/charts
    - ./logs:/opt/airflow/logs
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes: # <--- ESSA SEÇÃO ESTAVA FALTANDO DENTRO DO POSTGRES
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "airflow", "dags", "list", "--output", "json"]
      interval: 60s
      timeout: 30s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    command:
      - "bash"
      - "-c"
      - "airflow db init"
    depends_on:
      - postgres

volumes:
  postgres-db-volume: